server:
  port: 8081

spring:
  application:
    name: display

hystrix:
  command:
    productInfo:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      circuitBreaker:
        requestVolumeThreshold: 1
        errorThresholdPercentage: 50

product:
  ribbon:
#    listOfServers: localhost:8082, localhost:7777
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    server-url:
      defaultZone: http://127.0.0.1:8761/eureka

feign:
  hystrix:
    enabled: true